import os
import json
import streamlit as st
from openai import OpenAI
from utils.parser import parse_config

# ----------- LOAD API KEY -----------
api_key = st.secrets.get("OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

# ----------- PAGE CONFIG -----------
st.set_page_config(page_title="NetDoc AI", layout="wide")

# ----------- LOGO -----------
st.image("https://i.imgur.com/NU9cu5S.png", width=180)

# ----------- TITLE -----------
st.title("⚡ NetDoc AI — Autonomous Network Documentation Engine")
st.write("Upload Cisco configs → AI generates documentation, auditing & exports.")

# ----------- FILE UPLOAD -----------
uploaded_files = st.file_uploader(
    "Upload one or more config files",
    type=["txt", "cfg", "log"],
    accept_multiple_files=True
)

# ----------- MAIN TABS -----------
tab1, tab2, tab3, tab4 = st.tabs(
    ["📄 Overview", "🛡 Security Audit", "🗺 Topology", "📤 Export"]
)

# ⭕ TAB 1 — Overview -----------------------------------------
with tab1:
    st.subheader("📄 Overview Documentation")

    if uploaded_files and st.button("Generate Report"):
        combined = ""

        for f in uploaded_files:
            combined += f"\n\n# FILE: {f.name}\n"
            combined += f.read().decode("utf-8")

        with st.spinner("Processing configs..."):
            result = parse_config(combined)

        st.session_state["report"] = result
        st.session_state["report_markdown"] = json.dumps(result, indent=2)

        st.success("Report generated successfully!")
        st.json(result)

    else:
        st.info("Upload configs & click **Generate Report** to begin.")


# ⭕ TAB 2 — Security Audit -----------------------------------
with tab2:
    st.subheader("🛡 Security Audit (Coming in Step C-5)")

    if "report" in st.session_state:
        st.success("Security audit will be generated in the next step.")
    else:
        st.info("Generate a report first.")


# ⭕ TAB 3 — Topology -----------------------------------------
with tab3:
    st.subheader("🗺 AI Topology Diagram (Coming in Step C-6)")

    if "report" in st.session_state:
        st.success("Topology generation will be added in the next step.")
    else:
        st.info("Generate a report first.")


# ------------------- EXPORT SECTION -------------------
st.divider()
st.header("📤 Export Your Report")

if "report_markdown" not in st.session_state:
    st.info("Generate a report first to enable export options.")
else:
    md = st.session_state["report_markdown"]

    # ---- HTML EXPORT ----
    html_content = f"""
    <html>
    <head>
        <meta charset="UTF-8">
        <title>NetDoc AI Report</title>
        <style>
            body {{
                font-family: Arial;
                padding: 20px;
                line-height: 1.5;
            }}
            pre {{
                background: #f4f4f4;
                padding: 15px;
                border-radius: 6px;
                font-size: 13px;
            }}
        </style>
    </head>
    <body>
        <h2>NetDoc AI — Network Documentation Report</h2>
        <pre>{md}</pre>
        <hr>
        <p style="font-size:12px;color:gray;">Generated by NetDoc AI</p>
    </body>
    </html>
    """

    st.download_button(
        "🌐 Download HTML",
        data=html_content,
        file_name="NetDoc_Report.html",
        mime="text/html"
    )

    # ---- DOCX EXPORT ----
    from docx import Document
    doc = Document()
    doc.add_heading("NetDoc AI — Network Documentation Report", level=1)

    for line in md.split("\n"):
        doc.add_paragraph(line)

    doc_path = "NetDoc_Report.docx"
    doc.save(doc_path)

    with open(doc_path, "rb") as f:
        st.download_button(
            "📄 Download DOCX",
            data=f,
            file_name="NetDoc_Report.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        )

    # ---- PDF EXPORT (HTML → PDF via data URI method) ----
    import base64
    pdf_data_uri = (
        "data:application/pdf;base64,"
        + base64.b64encode(html_content.encode()).decode()
    )

    st.markdown(
        f'<a href="{pdf_data_uri}" download="NetDoc_Report.pdf">'
        f'<button style="padding:10px 20px;font-size:16px;">📘 Download PDF</button>'
        f'</a>',
        unsafe_allow_html=True
    )
